swagger: "2.0"
info:
  version: "1.0.0"
  title: Movie Data Base
host: localhost:3000
basePath: /api/mean
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /allMovies:
    get:
      description: Get all of the movies in the Data Base. 
      summary: Get all movies. 
      operationId: GetOperations
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          type: object
          properties:
            title: 
              type: string 
      responses:
        "200":
          description: success
          schema: 
            type: object
            properties: 
              title:
                type: string
        405:
          description: "Invalid input"
    post:
      tags:
      - "movie"
      summary: "Add a new pet to the store"
      description: ""
      operationId: "addPet"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          type: object
          properties:
            title: 
              type: string 
      responses:
        405:
          description: "Invalid input"
        200:
          description: "Success"
